//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amusoft.PCR.AM.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amusoft.PCR.AM.Shared.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from host.
        /// </summary>
        public static string Clipboard_LoadFromHost {
            get {
                return ResourceManager.GetString("Clipboard_LoadFromHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current.
        /// </summary>
        public static string Clipboard_TellCurrent {
            get {
                return ResourceManager.GetString("Clipboard_TellCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to host.
        /// </summary>
        public static string Clipboard_UpdateHost {
            get {
                return ResourceManager.GetString("Clipboard_UpdateHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Generic_Abort {
            get {
                return ResourceManager.GetString("Generic_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string Generic_ChangesSaved {
            get {
                return ResourceManager.GetString("Generic.ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Generic_Confirm {
            get {
                return ResourceManager.GetString("Generic_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate {0}.
        /// </summary>
        public static string Generic_Hibernate_0 {
            get {
                return ResourceManager.GetString("Generic.Hibernate_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Generic_Remove {
            get {
                return ResourceManager.GetString("Generic.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart {0}.
        /// </summary>
        public static string Generic_Restart_0 {
            get {
                return ResourceManager.GetString("Generic.Restart_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown {0}.
        /// </summary>
        public static string Generic_Shutdown_0 {
            get {
                return ResourceManager.GetString("Generic.Shutdown_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure ports.
        /// </summary>
        public static string HostsOverview_Configure {
            get {
                return ResourceManager.GetString("HostsOverview_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ports are configured..
        /// </summary>
        public static string HostsOverview_NoPortsConfigured {
            get {
                return ResourceManager.GetString("HostsOverview_NoPortsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client clipboard updated.
        /// </summary>
        public static string InputControl_ClientUpdatedMessage {
            get {
                return ResourceManager.GetString("InputControl.ClientUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string InputControl_Clipboard {
            get {
                return ResourceManager.GetString("InputControl.Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application control.
        /// </summary>
        public static string InputControl_ControlOptions {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string InputControl_ControlOptions_Forward {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string InputControl_ControlOptions_Fullscreen {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string InputControl_ControlOptions_Reverse {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video browser.
        /// </summary>
        public static string InputControl_ControlOptions_VideoBrowser {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.VideoBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string InputControl_ControlOptions_VideoBrowser_MuteToggle {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.VideoBrowser.MuteToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string InputControl_ControlOptions_VideoBrowser_PlayToggle {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.VideoBrowser.PlayToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume.
        /// </summary>
        public static string InputControl_ControlOptions_VolumeDown {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        public static string InputControl_ControlOptions_VolumeUp {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string InputControl_ControlOptions_Windows {
            get {
                return ResourceManager.GetString("InputControl.ControlOptions.Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string InputControl_Down {
            get {
                return ResourceManager.GetString("InputControl.Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string InputControl_Enter {
            get {
                return ResourceManager.GetString("InputControl.Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string InputControl_Escape {
            get {
                return ResourceManager.GetString("InputControl.Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host clipboard updated.
        /// </summary>
        public static string InputControl_HostUpdatedMessage {
            get {
                return ResourceManager.GetString("InputControl.HostUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string InputControl_Left {
            get {
                return ResourceManager.GetString("InputControl.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control mouse.
        /// </summary>
        public static string InputControl_MouseControl {
            get {
                return ResourceManager.GetString("InputControl.MouseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string InputControl_Right {
            get {
                return ResourceManager.GetString("InputControl.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send input.
        /// </summary>
        public static string InputControl_SendInput {
            get {
                return ResourceManager.GetString("InputControl.SendInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string InputControl_Space {
            get {
                return ResourceManager.GetString("InputControl.Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string InputControl_Up {
            get {
                return ResourceManager.GetString("InputControl.Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick audio source.
        /// </summary>
        public static string InputControl_Windows_PickAudioSource {
            get {
                return ResourceManager.GetString("InputControl.Windows.PickAudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Monitors_Brightness {
            get {
                return ResourceManager.GetString("Monitors.Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness: {0}.
        /// </summary>
        public static string Monitors_Brightness_0 {
            get {
                return ResourceManager.GetString("Monitors.Brightness_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Monitors_Off {
            get {
                return ResourceManager.GetString("Monitors.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Monitors_On {
            get {
                return ResourceManager.GetString("Monitors.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity: {0}.
        /// </summary>
        public static string MouseControl_Sensitivity {
            get {
                return ResourceManager.GetString("MouseControl.Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Nav_Audio {
            get {
                return ResourceManager.GetString("Nav.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input control.
        /// </summary>
        public static string Nav_InputControl {
            get {
                return ResourceManager.GetString("Nav.InputControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string Nav_Monitors {
            get {
                return ResourceManager.GetString("Nav.Monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control mouse.
        /// </summary>
        public static string Nav_MouseControl {
            get {
                return ResourceManager.GetString("Nav.MouseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Nav_Programs {
            get {
                return ResourceManager.GetString("Nav.Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System state.
        /// </summary>
        public static string Nav_SystemState {
            get {
                return ResourceManager.GetString("Nav.SystemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio mixer.
        /// </summary>
        public static string Page_Title_Audio {
            get {
                return ResourceManager.GetString("Page.Title.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Page_Title_HostsOverview {
            get {
                return ResourceManager.GetString("Page.Title.HostsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Remote 3.
        /// </summary>
        public static string Page_Title_MainPage {
            get {
                return ResourceManager.GetString("Page.Title.MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Page_Title_Settings {
            get {
                return ResourceManager.GetString("Page.Title.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill program.
        /// </summary>
        public static string Programs_KillProgram {
            get {
                return ResourceManager.GetString("Programs.KillProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start program.
        /// </summary>
        public static string Programs_StartProgram {
            get {
                return ResourceManager.GetString("Programs.StartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a number.
        /// </summary>
        public static string Settings_AddNumber {
            get {
                return ResourceManager.GetString("Settings.AddNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add port.
        /// </summary>
        public static string Settings_AddPorts {
            get {
                return ResourceManager.GetString("Settings_AddPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert a number.
        /// </summary>
        public static string Settings_FailedToInsertPort {
            get {
                return ResourceManager.GetString("Settings.FailedToInsertPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Port.
        /// </summary>
        public static string Settings_NewPort {
            get {
                return ResourceManager.GetString("Settings.NewPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port already exists.
        /// </summary>
        public static string Settings_PortAlreadyExists {
            get {
                return ResourceManager.GetString("Settings.PortAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string SystemState_Abort {
            get {
                return ResourceManager.GetString("SystemState.Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        public static string SystemState_Hibernate {
            get {
                return ResourceManager.GetString("SystemState.Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string SystemState_Lock {
            get {
                return ResourceManager.GetString("SystemState.Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick delay.
        /// </summary>
        public static string SystemState_PickDelay {
            get {
                return ResourceManager.GetString("SystemState.PickDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string SystemState_Restart {
            get {
                return ResourceManager.GetString("SystemState.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string SystemState_Shutdown {
            get {
                return ResourceManager.GetString("SystemState.Shutdown", resourceCulture);
            }
        }
    }
}
