//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amusoft.PCR.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amusoft.PCR.Application.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Generic_Remove {
            get {
                return ResourceManager.GetString("Generic.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure ports.
        /// </summary>
        public static string HostsOverview_Configure {
            get {
                return ResourceManager.GetString("HostsOverview_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ports are configured..
        /// </summary>
        public static string HostsOverview_NoPortsConfigured {
            get {
                return ResourceManager.GetString("HostsOverview_NoPortsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Nav_Audio {
            get {
                return ResourceManager.GetString("Nav.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input control.
        /// </summary>
        public static string Nav_Input {
            get {
                return ResourceManager.GetString("Nav.Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string Nav_Monitors {
            get {
                return ResourceManager.GetString("Nav.Monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Nav_Programs {
            get {
                return ResourceManager.GetString("Nav.Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System state.
        /// </summary>
        public static string Navi_SystemState {
            get {
                return ResourceManager.GetString("Navi.SystemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio mixer.
        /// </summary>
        public static string Page_Title_Audio {
            get {
                return ResourceManager.GetString("Page.Title.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Page_Title_HostsOverview {
            get {
                return ResourceManager.GetString("Page.Title.HostsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Remote 3.
        /// </summary>
        public static string Page_Title_MainPage {
            get {
                return ResourceManager.GetString("Page.Title.MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Page_Title_Settings {
            get {
                return ResourceManager.GetString("Page.Title.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add port.
        /// </summary>
        public static string Settings_AddPorts {
            get {
                return ResourceManager.GetString("Settings_AddPorts", resourceCulture);
            }
        }
    }
}
